{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "gocicd.serviceAccountName" . }}
  labels:
{{ include "gocicd.labels" . | indent 4 }}
{{- end -}}
